config/routes.rb
Rails.application.routes.draw do
  resources :account_charts
  resources :invoice_lines
  resources :invoices
  resources :customers


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


 resources :account_charts ,only: [:index, :new, :create, :show]
 resources :invoices, only: [:index, :new, :create, :show]


 resources :invoices, only: [:index, :new, :create, :show, :edit, :update, :destroy]


# routes for adding fields dynamically
  get '/add_field', to: 'invoices#add_field', as: 'add_field'
  post '/add_field', to: 'invoices#add_field'



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
#resources:flowdash
   #get 'flowdash/:page' => 'flowdash#show', as: 'flowdash'
get 'flowdash/:page' => 'flowdash#show', as: 'flowdash'
 root 'flowdash/flowdash#index';

end

app/models/account_chart.rb
class AccountChart < ApplicationRecord
end

app/controllers/account_charts_controller.rb
class AccountChartsController < ApplicationController
  before_action :set_account_chart, only: %i[ show edit update destroy ]

  # GET /account_charts or /account_charts.json
  def index
    @account_charts = AccountChart.all
  end

  # GET /account_charts/1 or /account_charts/1.json
  def show
  end

  # GET /account_charts/new
  def new
    @account_chart = AccountChart.new
  end

  # GET /account_charts/1/edit
  def edit
  end

  # POST /account_charts or /account_charts.json
  def create
    @account_chart = AccountChart.new(account_chart_params)

    respond_to do |format|
      if @account_chart.save
        format.html { redirect_to account_chart_url(@account_chart), notice: "Account chart was successfully created." }
        format.json { render :show, status: :created, location: @account_chart }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @account_chart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /account_charts/1 or /account_charts/1.json
  def update
    respond_to do |format|
      if @account_chart.update(account_chart_params)
        format.html { redirect_to account_chart_url(@account_chart), notice: "Account chart was successfully updated." }
        format.json { render :show, status: :ok, location: @account_chart }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @account_chart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /account_charts/1 or /account_charts/1.json
  def destroy
    @account_chart.destroy

    respond_to do |format|
      format.html { redirect_to account_charts_url, notice: "Account chart was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account_chart
      @account_chart = AccountChart.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def account_chart_params
      params.require(:account_chart).permit(:account_name, :ctype, :category, :class, :balance)
    end
end

app/helpers/account_charts_helper.rb
module AccountChartsHelper
end

app/views/account_charts/_form.html.erb
<%= form_with(model: account_chart) do |form| %>
  <% if account_chart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(account_chart.errors.count, "error") %> prohibited this account_chart from being saved:</h2>

      <ul>
        <% account_chart.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :account_name %>
    <%= form.text_area :account_name %>
  </div>

  <div class="field">
    <%= form.label :ctype %>
    <%= form.text_area :ctype %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_area :category %>
  </div>

  <div class="field">
    <%= form.label :class %>
    <%= form.text_area :class %>
  </div>

  <div class="field">
    <%= form.label :balance %>
    <%= form.text_field :balance %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/account_charts/edit.html.erb
<h1>Editing Account Chart</h1>

<%= render 'form', account_chart: @account_chart %>

<%= link_to 'Show', @account_chart %> |
<%= link_to 'Back', account_charts_path %>

app/views/account_charts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Account Charts</h1>

<table>
  <thead>
    <tr>
      <th>Account name</th>
      <th>Ctype</th>
      <th>Category</th>
      <th>Class</th>
      <th>Balance</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @account_charts.each do |account_chart| %>
      <tr>
        <td><%= account_chart.account_name %></td>
        <td><%= account_chart.ctype %></td>
        <td><%= account_chart.category %></td>
        <td><%= account_chart.class %></td>
        <td><%= account_chart.balance %></td>
        <td><%= link_to 'Show', account_chart %></td>
        <td><%= link_to 'Edit', edit_account_chart_path(account_chart) %></td>
        <td><%= link_to 'Destroy', account_chart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Account Chart', new_account_chart_path %>

app/views/account_charts/index2.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="keywords" content="tree, treegrid, tree grid, hirarchy, hirarchical, parent child" />
    <meta
      name="description"
      content="This example demonstrates how to perform two tasks: customizing the hierarchical tree column&#x27;s presentation and adding a formula to the group footers."
    />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Chart of Accounts | Data Views | GrapeCity DataViewsJS JavaScript Demos</title>

    <link href="https://www.grapecity.com/dataviewsjs/demos/node_modules/normalize.css/normalize.css" rel="stylesheet" type="text/css" />
    <link href="https://www.grapecity.com/dataviewsjs/demos/static/css/base.css" rel="stylesheet" type="text/css" />
    <link href="https://www.grapecity.com/dataviewsjs/demos/static/dataviews/gc.dataviews.core.min.css" rel="stylesheet" type="text/css" />
    <link href="https://www.grapecity.com/dataviewsjs/demos/static/dataviews/gc.dataviews.grid.min.css" rel="stylesheet" type="text/css" />
    <link href="styles.css" rel="stylesheet" type="text/css" />

    <script src="https://www.grapecity.com/dataviewsjs/demos/static/js/app-polyfills.min.js" type="text/javascript"></script>

    <script type="text/javascript">
      window.process = {
        env: {
          NODE_ENV: 'production',
          USE_NPM: false,
          USE_CDN: false,
          SITE_ROOT: 'https://www.grapecity.com/dataviewsjs/demos',
          FRAMEWORK: 'purejs',
          DVJS_LICENSE_KEY:
            'GrapeCity-Internal-Use-Only,GrapeCity,E195393772372914#B0KV4Ny56Vr5Wb7w6buJWeGRWb4NXUnNXRlFWWXl6SoN5VzVkYslmQ95WTENkTllVQzd4QhpEejdDNJZlWOp6M7oERQNnWspkaaB5QMhnR7dmUkRnVJR4L5cHTKNkZZdDbRBzZIxmSSR6NrpVQaVUQrBlc6ImYysSd4UlUEZGbw2kMl9UOzQVMId6ZXtUN83CO5RzaZt4VY5kM5pkUGpUUUV7UExUeGpUdTV5dFJ4bPhTc8pGeXJHWrkzNlFzdUtWTr5UQDdVckdGbSVUWr2yMPNzctZVRxEEW9lEbsZHUKJnVaRXT5p6Z0tWMqJGVrtSTIZnaopGSWZXbVNjY0hzQB5We4dnUr3ER8MkI0IyUiwiIGZUNwEkN5MjI0ICSiwSM9ETO6czNygTM0IicfJye#4Xfd5nIZRVV9IiOiMkIsISM6ByUKN7dllmVhRXYEJiOi8kI1tlOiQmcQJCLiEDMzATOwAyMwgDMwIDMyIiOiQncDJCLiI7au26YukHdpNWZwFmcn9iKsAnau26YukHdpNWZwFmcn9iKs86Yu46bj9Se4l6YlBXYydmLqwSbvNmL6VGZ9RXajVGchJ7ZuoCLt36YukHdpNWZwFmcn9iKiojIz5GRiwiI9RXaDVGchJ7RiojIh94QiwSZ5JHd0ICb6VkIsICNxkjM7MjM7czM9MTN9EjI0ICZJJye0ICRiwiI34zZN3yZGNlUnJDe5wkQPVlcBh7SppmUNBlU9dWS7J4ZMRES4MTZkRXTxM7Uq5GeQdHcyFHVup6dQd6ZDpEVrNDSh9kbNdzZrl4dwdPQ',
          SJS_LICENSE_KEY:
            '*.grapecity.com,E613631884219496#B0qRgJHWSJ7NyBlc8BjNMRHW7g7YldTZXFTQuFnW4hVOCplVSlVV09ERlhEZuVTVKlTazE4Q6VGSw2CdWZUWSVmbjVXbrxmWFVWR8ZzQro7U84WMGdlbuVHb73kS5kjUTN4NvFVdLdXWVR4Nox6Z7UUSysEcXJEMsN6bDN4TxMDVwVmWBRzKxhkTzAXTaJmdD3CRFJTd8R4R6M5RklWa6oUaLlXMwR4R8ZUdtRWVxUUaQh6VXNDdEhlZ7FHR6QXTPJTVvkWcyZnbSdHRtZHcYF6TKN4axYGcZNjTDF7TvFTTr24VqZjVHVjcLd7QkRmdNxkI0IyUiwiI5gDOEF4QGVjI0ICSiwiMzkTO9kTOyMTM0IicfJye35XX3JSSGljQiojIDJCLiITMuYHITpEIkFWZyB7UiojIOJyebpjIkJHUiwiI4MDMyEDMgkDM8ATOxAjMiojI4J7QiwiIt36YukHdpNWZwFmcn9iKiojIz5GRiwiIj9WagkHdpNUZwFmcHJiOiEmTDJCLlVnc4pjIsZXRiwiI6kDN9EjM4gDOxMjNzEjNiojIklkIs4XZzxWYmpjIyNHZisnOiwmbBJye0ICRiwiI34TQ72kNBV6YXpXdGxGWxdHcol4MyUGUHJVbQVHRx44Sw84YxRkS4QnZadDNmhWWxV5QxFlTlZEbBJ5N8gUNQlDb7J6Kl36YHVnb4NGN92UMFdlNORFU8VDSaFlQSVlS4EHTrA5Ohh',
        },
      };
    </script>

    <script src="https://www.grapecity.com/dataviewsjs/demos/static/dataviews/gc.dataviews.common.min.js" type="text/javascript"></script>
    <script src="https://www.grapecity.com/dataviewsjs/demos/static/dataviews/gc.dataviews.core.min.js" type="text/javascript"></script>
    <script src="https://www.grapecity.com/dataviewsjs/demos/static/dataviews/gc.dataviews.grid.min.js" type="text/javascript"></script>

    <script src="https://www.grapecity.com/dataviewsjs/demos/static/js/license.js" type="text/javascript"></script>
  </head>

  <body>
   

<p id="notice"><%= notice %></p>

<h1>Account Charts</h1>

<table>
  <thead>
    <tr>
      <th>Account name</th>
      <th>Type</th>
      <th>Category</th>
      <th>Class</th>
      <th>Balance</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @account_charts.each do |account_chart| %>
      <tr>
        <td><%= account_chart.account_name %></td>
        <td><%= account_chart.type %></td>
        <td><%= account_chart.category %></td>
        <td><%= account_chart.class %></td>
        <td><%= account_chart.balance %></td>
        <td><%= link_to 'Show', account_chart %></td>
        <td><%= link_to 'Edit', edit_account_chart_path(account_chart) %></td>
        <td><%= link_to 'Destroy', account_chart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Account Chart', new_account_chart_path %>


  </body>
</html>

app/views/account_charts/new.html.erb
<h1>New Account Chart</h1>

<%= render 'form', account_chart: @account_chart %>

<%= link_to 'Back', account_charts_path %>

app/views/account_charts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Account name:</strong>
  <%= @account_chart.account_name %>
</p>

<p>
  <strong>Ctype:</strong>
  <%= @account_chart.ctype %>
</p>

<p>
  <strong>Category:</strong>
  <%= @account_chart.category %>
</p>

<p>
  <strong>Class:</strong>
  <%= @account_chart.class %>
</p>

<p>
  <strong>Balance:</strong>
  <%= @account_chart.balance %>
</p>

<%= link_to 'Edit', edit_account_chart_path(@account_chart) %> |
<%= link_to 'Back', account_charts_path %>