config/routes.rb
Rails.application.routes.draw do
  resources :account_charts
  resources :invoice_lines
  resources :invoices
  resources :customers


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


 resources :account_charts ,only: [:index, :new, :create, :show]
 resources :invoices, only: [:index, :new, :create, :show]


 resources :invoices, only: [:index, :new, :create, :show, :edit, :update, :destroy]


# routes for adding fields dynamically
  get '/add_field', to: 'invoices#add_field', as: 'add_field'
  post '/add_field', to: 'invoices#add_field'



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
#resources:flowdash
   #get 'flowdash/:page' => 'flowdash#show', as: 'flowdash'
get 'flowdash/:page' => 'flowdash#show', as: 'flowdash'
 root 'flowdash/flowdash#index';

end

app/models/invoice.rb
class Invoice < ApplicationRecord
  has_many :invoice_lines
    accepts_nested_attributes_for :invoice_lines




#accepts_nested_attributes_for :invoice_lines


	def invoice_lines_attributes=(hash)
		    if !!self.id
		      self.invoice_lines.clear
		      hash.values.each do |attributes|
			attrs = attributes.merge({invoice_id: self.id})
			self.invoice_lines << InvoiceLine.find_or_create_by(attrs)
		      end
		    end
		  end








   

end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: %i[ show edit update destroy ]
  before_action :find_invoice, only: [:show, :edit, :update, :destroy]

  # GET /invoices or /invoices.json
  def index
    @invoices = Invoice.all
  end

  # GET /invoices/1 or /invoices/1.json
  def show
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
    @invoice.invoice_lines.build
  end

  # GET /invoices/1/edit 
  def edit
  end

  # POST /invoices or /invoices.json
 #  def create
   #  @invoice = Invoice.new(invoice_params)

   #  respond_to do |format|
     #  if @invoice.save
      #  format.html { redirect_to invoice_url(@invoice), notice: "Invoice was successfully created." }
       #  format.json { render :show, status: :created, location: @invoice }
     #  else
      #   format.html { render :new, status: :unprocessable_entity }
       #  format.json { render json: @invoice.errors, status: :unprocessable_entity }
      # end
   #  end
 #  end




def create
    @invoice = invoices.build(invoice_params)
    invoice_params[:invoice_lines_attributes].each do |num,product|
      @invoice.invoice_pros.build(product)
   
end 
   
      flash[:alert] = @invoice.errors.full_messages.uniq
      render :new
    
  end









  # PATCH/PUT /invoices/1 or /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to invoice_url(@invoice), notice: "Invoice was successfully updated." }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end









  # DELETE /invoices/1 or /invoices/1.json
  def destroy
    @invoice.destroy

    respond_to do |format|
      format.html { redirect_to invoices_url, notice: "Invoice was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def add_field
    respond_to do |format|
      format.js {render layout: false}
    end
  end




  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def invoice_params
      params.require(:invoice).permit(:customer_no, :custoner_name, :contactno, :contact_name, :address, :city, :date, :sale_person_code, :sale_person_name, invoice_lines_attributes: [:charge_type, :item_no, :description, :quantity, :unit_of_measure, :unit_price, :amount, :_destroy])
    end






def find_invoice
   @invoice = Invoice.find_by(id: params[:id])
  end

end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/myolds/_field.html.erb
<tr id="row-0 input-group">
  <th scope="row" id="product-num"></th>

  <div class="field">
  </div>
 
  <!-- <td><%#<%= ff.select :product_id, options_from_collection_for_select(Product.all, :id, :name), include_blank: 'Select a product' %></td> -->

 <td><%= ff.text_field :charge_type, size: '1em', class: 'form-control text-center'  %></t

  <div class="field">
  </div>
  <td><%= ff.text_field :item_no, size: '1em', class: 'form-control text-center'  %></td>

  <div class="field">
  </div>
  <td><%= ff.text_field :description, size: '2em', class: 'form-control text-center' %></td>
  <div class="field">
  </div>

 <td><%= ff.text_field :quantity, size: '2em', class: 'form-control text-center' %></td>
  <div class="field">
  </div>
 <td><%= ff.text_field :unit_price, size: '2em', class: 'form-control text-center' %></td>
  <div class="field">
  </div>
 <td><%= ff.text_field :amount, size: '5em', class: 'form-control text-center' %></td>
  <div class="field">
  </div>


  <td><%= link_to "Delete", "", class: 'btn btn-danger float-right remove-field' %></td>
</tr>





 

  

  

app/views/invoices/myolds/_form1.html.erb
<%= form_with(model: invoice) do |form| %>
  <% if invoice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(invoice.errors.count, "error") %> prohibited this invoice from being saved:</h2>

      <ul>
        <% invoice.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>



  <div class="field">
    <%= form.label :customer_no %>
    <%= form.text_area :customer_no %>
  </div>

  <div class="field">
    <%= form.label :custoner_name %>
    <%= form.text_area :custoner_name %>
  </div>

  <div class="field">
    <%= form.label :contactno %>
    <%= form.text_area :contactno %>
  </div>

  <div class="field">
    <%= form.label :contact_name %>
    <%= form.text_area :contact_name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_area :address %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_area :city %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="field">
    <%= form.label :sale_person_code %>
    <%= form.text_area :sale_person_code %>
  </div>

  <div class="field">
    <%= form.label :sale_person_name %>
    <%= form.text_area :sale_person_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/invoices/myolds/_invoice_form.html.erb
<%= form_for invoice do |f| %>

  <div class="row">

    <div class="col">
      <h4>Users Business Name</h4>
      <address class="">
        1 Address Here City, State 00000 (user address)
      </address>
    </div>

    <div class="col">
      <span class="inline-headers">
        <h2>Invoice ID: <%= invoice.id || Invoice.all.count+1 %>  </h2>
      </span>

    </div>
  </div>

  <div class="row">
    <div class="col">
      <h4>Bill To Account</h4>

      <% if !!params[:account_id] %>
        <%= f.collection_select(:account_id, current_user.accounts, :id, :name, {}, {class: 'form-control custom-input'}) %>
      <% else %>
        <div class="field">
          <%= f.select(:account_id, current_user.accounts.collect {|a| [a.name, a.id]}, prompt: "Select Account", class: 'form-control custom-input') %>
        </div>
      <% end %>

      <br>
      <%= link_to "Create New Account", new_account_path %>
    </div>

    <div class="col">
      <div class="field">
        <h5>Date Created: <%= f.date_field  :created_at, value: Time.now.strftime('%Y-%m-%d'), class: 'form-control date-select'  %></h5>
      </div>
      <br>
        <div class="field">
          <h5>Date Due: <%= f.date_field :due_time, value: (Time.now+7*86400).strftime('%Y-%m-%d'), class: 'form-control date-select' %> </h5>
        </div>
    </div>
  </div>

  <div class="row border border-dark bg-dark">
    <div class="col">
      <table class="table table-dark">
        <thead class="text-center">
          <tr>
            <th scope="col">#</th>
            <th scope="col" class='text-left'>Product</th>
            <th scope="col">Quantity</th>
            <th scope="col"></th>
          </tr>
        </thead>

        <tbody id="table-body" class="fields" >

          <% @invoice.invoice_lines.each do |invoice_line| %>
            <%= f.fields_for :invoice_lines,product do |ff| %>
              <%= render partial: 'invoice_line_field', locals: {ff: ff} %>
            <% end %>
          <% end %>
        </tbody>

      </table>

    </div>
  </div>

  <div class="row border border-dark p-2">
    <%= link_to "Add Product", add_field_path(format: :js), {method: :post, remote: true, id: "addProductBtn", class: 'btn btn-primary'} %>

    <div class="col">

    </div>

    <div class="col">
      <div class="row">
        <div class="col">
          Sub Total:
        </div>
        <div class="col">
          <!--  we need to fix the precision on the totals at some point -->
          $ <%= @invoice.amount_due %>
        </div>
      </div>

      <div class="row font-weight-bold">
        <div class="col">
          Grand Total Due:
        </div>
        <div class="col">
          <!--  we need to fix the precision on the totals at some point -->
          $ <%= @invoice.grand_total unless request.url.match('/invoices/new')%>
        </div>
      </div>
    </div>
  </div>


  <div class="row action">
    <div class="col-10">
    </div>

    <div class="float-right col-2">
      <%= f.submit class: 'btn btn-primary mt-3' %>
    </div>

  </div>

<script type="text/javascript">

  function showTotal(e){
    alert('workin');
  }

  function deleteRow(row){
    row.parentNode.deleteRow(row.rowIndex-1);
    return true;
  }

  document.addEventListener('click', (e) => {
    if (e.target.id == 'delete-row'){
      e.target.parentElement.parentElement.parentElement.removeChild(e.target.parentElement.parentElement)
      numberProducts()
    }
  })

  var deleteBtns = document.getElementsByClassName("remove-field");

  for (var i=0; i<deleteBtns.length; i++){
    deleteBtns[i].addEventListener('click', function(e){
      e.target.parentElement.parentElement.parentElement.removeChild(e.target.parentElement.parentElement)
    });
  }

  document.addEventListener("DOMContentLoaded", function(){

    let tBody = document.getElementById("table-body");
    let addBtn = document.getElementById("addProductBtn");

    function nameFields(){
      let selects = tBody.getElementsByTagName('select');
      for (var i=0;i < selects.length; i++){
        // selects[i].name = "invoice[invoice_lines_attributes][" +i+ "][invoice_line_id]";
        selects[i].name = `invoice[invoice_products_attributes][${i}][invoice_line_id]`;
        selects[i].id = `invoice[invoice_products_attributes][${i}][invoice_line_id]`;
        selects[i].parentElement.previousSibling.previousSibling.innerHTML = (i+1);
        // selects[i].parentNode.nextSibling.nextElementSibling.firstElementChild.name = "invoice[invoice_lines_attributes]["+i+"][quantity]";
        selects[i].parentNode.nextSibling.nextElementSibling.firstElementChild.name = `invoice[invoice_lines_attributes][${i}][quantity]`;
        // selects[i].parentNode.nextSibling.nextElementSibling.firstElementChild.id = "invoice[invoice_lines_attributes]["+i+"][quantity]";
        selects[i].parentNode.nextSibling.nextElementSibling.firstElementChild.id = `invoice[invoice_lines_attributes][${i}][quantity]`;
      }
    }


    addBtn.addEventListener('click', function(){
      setTimeout(nameFields, 300);
    })

    numberProducts();
  });

  function numberProducts(){
    debugger
    let tBody = document.getElementById("table-body");
    let selects = tBody.getElementsByTagName('tr');
    for (var i=0;i < selects.length; i++){
      selects[i].firstElementChild.innerText = i+1;
    }
  }


</script>
<% end %>

app/views/invoices/myolds/_invoice_product.html.erb
  <tr id="row-0">
    <th scope="row" id="product-num" colspan="1">0</th>
   
    <td><%= invoice_line_field.text_field :charge_type, class: 'col-md-3' %></td>
    <td><%= invoice_line_field.text_field :item_no, class: 'col-md-3' %></td>
    <td><%= invoice_line_field.text_field :description, class: 'col-md-3' %></td>
    <td><%= invoice_line_field.text_field :quantity, class: 'col-md-3' %></td>
    <td><%= invoice_line_field.text_field :unit_price, class: 'col-md-3' %></td>
    <td><%= invoice_line_field.text_field :amount, class: 'col-md-3' %></td>

    <td><%= link_to "Delete", "#", class: 'remove-field' %></td>
    <%= invoice_line_field.hidden_field :_destroy, as: :hidden %>


  </tr>

app/views/invoices/myolds/_invoice_product_field.html.erb
  <tr id="input-group">

    <th scope="row" id="product-num" class='text-center'></th>

    <td><input size="2em" class="form-control text-center" type="text" value=" " charge_type="invoice[invoice_lines_attributes][ ][charge_type]" id="invoice_invoice_lines_attributes_ _charge_type"></td>

    <td><input size="2em" class="form-control text-center" type="text" value=" " item_no="invoice[invoice_lines_attributes][ ][item_no]" id="invoice_invoice_lines_attributes_0_item_no"></td>

<td><input size="2em" class="form-control text-center" type="text" value=" " description="invoice[invoice_lines_attributes][0][description]" id="invoice_invoice_lines_attributes_0_description"></td>


<td><input size="2em" class="form-control text-center" type="text" value=" " quantity="invoice[invoice_lines_attributes][0][quantity]" id="invoice_invoice_lines_attributes_0_quantity"></td>


<td><input size="2em" class="form-control text-center" type="text" value=" " unit_price="invoice[invoice_lines_attributes][0][unit_price]" id="invoice_invoice_lines_attributes_0_unit_price"></td>

<td><input size="2em" class="form-control text-center" type="text" value=" " amount="invoice[invoice_lines_attributes][0][amount]" id="invoice_invoice_lines_attributes_0_amount"></td>




    <td><a class="btn btn-danger float-right remove-field" id='delete-row' href="">Delete</a></td>

  </tr>

app/views/invoices/myolds/_show_invoice.html.erb
<div class="row mb-5">

  <div class="col">
    
    <%= link_to "Edit", edit_invoice_path(@invoice), class: 'btn btn-warning' %>
    <%= link_to "Delete", invoice_path(@invoice), method: :delete, class: 'btn btn-danger float-right' %>
  </div>

</div>

<div class="row">
  <div class="col">
  
  </div>


  <div class="col">
  
  </div>
</div>


<div class="row p-2 border-right border-left border-top border-dark">

  <div class="col">
    <h4>Users Business Name</h4>
    <address class="">
      1 Address Here City, State 00000 (user address)
    </address>
  </div>

  <div class="col">
    <h2>Invoice #: <%= @invoice.id %></h2>
  </div>
</div>

<div class="row border-left border-right border-dark">

  <div class="col m-4">
    <h4>Bill To</h4>
    
  </div>

  <div class="col">
    
  </div>
</div>

<div class="row border border-dark bg-dark">
  <div class="col">
    <table class="table table-dark">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Charge Type</th>
          <th scope="col">Item No</th>
          <th scope="col">Description</th>
          <th scope="col">Quantity</th>
          <th scope="col">Unit of Measure</th>
          <th scope="col">Unit Price</th>
          <th scope="col">Amount</th>
         
        </tr>
      </thead>
      <tbody>
00/invoices/1/edit
        <% @invoice.invoice_lines do |invoice_line| %>
       
          <tr>
            <th scope="row" colspan="1"><%= invoice.id %></th>
            <td><%= invoice_lines.charge_type %></td>
            <td><%= invoice_lines.item_no %></td>
            <td><%= invoice_lines.description %></td>
            <td><%= invoice_lines.quantity %></td>
            <td><%= invoice_lines.unit_of_measure %></td>
            <td><%= invoice_lines.unit_price %></td>
            <td><%= invoice_lines.amount %></td>
            
          </tr>

        <% end %>

      </tbody>
    </table>


  </div>
</div>

<br>

<div class="row bg-info text-white pt-2 pb-">

  <div class="col-7">

  </div>

  <div class="col-5">
    <div class="row">
      <div class="col">
        Sub Total:
      </div>
      <div class="col">
        <!--  we need to fix the precision on the totals at some point -->
       
      </div>
    </div>

    <div class="row font-weight-bold">
      <div class="col">
        Grand Total Due:
      </div>
      <div class="col">
        <!--  we need to fix the precision on the totals at some point -->
       
      </div>
    </div>
  </div>
</div>

app/views/invoices/myolds/add_field.js.erb
$("#table-body").append(`
  <tr id="input-group">
    <th scope="row" id="product-num"></th>
    
    <td><input size="1em" class="form-control text-center" type="text" value="1" name="invoice[invoice_lines_attributes][0][charge_type]" id="invoice_invoice_lines_attributes_0_charge_type"></td>
    
    
   <td><input size="1em" class="form-control text-center" type="text" value="1" name="invoice[invoice_lines_attributes][0][item_no]" id="invoice_invoice_lines_attributes_0_quantity"></td>


  <td><input size="1em" class="form-control text-center" type="text" value="1" description="invoice[invoice_lines_attributes][0][description]" id="invoice_invoice_lines_attributes_0_description"></td>

<td><input size="1em" class="form-control text-center" type="text" value="1" quantity="invoice[invoice_lines_attributes][0][quantity]" id="invoice_invoice_lines_attributes_0_quantity"></td>

<td><input size="1em" class="form-control text-center" type="text" value="1" unit_price="invoice[invoice_lines_attributes][0][unit_price]" id="invoice_invoice_lines_attributes_0_quantity"></td>

<td><input size="1em" class="form-control text-center" type="text" value="1" amount="invoice[invoice_lines_attributes][0][amount]" id="invoice_invoice_lines_attributes_0_amount"></td>

<br>


    <td><a class="btn btn-danger float-right remove-field" id="delete-row">Delete</a></td>



  </tr>
`)

app/views/invoices/myolds/edit.html.erb
<h1>Editing Invoice</h1>
<%= form_for @invoice, url: {controller: 'invoices', action: 'update', id: @invoice  } do |f| %>
    <% hidden_field_tag(:invoice, :id) %>



<div class="container-fluid page__heading-container">
  <div class="page__heading d-flex align-items-center d-print-none">
    <div class="flex">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb mb-0">
        <li class="breadcrumb-item"><a href="#"><i class="material-icons icon-20pt">home</i></a></li>
        <li class="breadcrumb-item">Pages</li>
        <li class="breadcrumb-item active" aria-current="page">Invoice</li>
      </ol>
    </nav>    
    <h1 class="m-0">Invoice</h1>
    </div>
    <a href="#" class="btn btn-primary"><i class="material-icons">file_download</i> Download</a>
  </div>
</div>
<div class="container-fluid page__container">
  
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <div class="card">
        <div class="card-body">
            <div class="badge badge-danger">OVERDUE</div>
          
          <div class="px-3">
            <div class="d-flex justify-content-center flex-column text-center my-5 navbar-light">
              <a href="<%= flowdash_path(:index) %>" class="navbar-brand d-flex flex-column m-0" style="min-width: 0">
                <img class="navbar-brand-icon mb-2" src="<%= image_path('flowdash/stack-logo-blue.svg')%>" width="25" alt="Stack">
                <span>Invoice</span>
              </a>
              <div class="text-muted">Invoice #MPS1234AD</div>
            </div>
            <div class="row mb-5">
              

              <div class="col-lg text-left">
                <div class="text-label">TO (CUSTOMER)</div>
                <p class="mb-3">
                  <strong class="text-body">
                 <%= f.text_area :customer_no, {class: 'form-control'} %>
                 <%= f.text_area :custoner_name, {class: 'form-control'} %>

                </strong><br>
                  3700 George Avenue<br>
                  Mobile, AL 36602<br>
                </p>
                <div class="text-label">Due date</div>
                Nov 1st, 2018
              </div>


               <div class="col-lg-right">
                <div class="text-label">Invoice NUMBER</div>
                #MPS1234AD
              </div>
              
           
    
            <div class="table-responsive">
              <table class="table border-bottom mb-5">
                <thead>
                  <tr class="bg-light">
                    <th>Description</th>
                    <th>Hours</th>
                    <th class="text-right">Cost</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td>Layout &amp; Sidebar Design</td>
                    <td>200</td>
                    <td class="text-right">&dollar;2,500</td>
                  </tr>
                  <tr>
                    <td>Concept</td>
                    <td>2</td>
                    <td class="text-right">&dollar;1000</td>
                  </tr>
                  <tr >
                    <td><strong>Total amount due</strong></td>
                    <td colspan="2" class="text-right"><strong>&dollar;3,500</strong></td>
                  </tr>
                </tbody>
              </table>
            </div>




            
            <div class="text-label">Notes</div>
            <p class="text-muted">We appreciate your business. Should you need us to add VAT or extra notes let us know!</p>
          </div>
        </div>
      </div>

 <div class="table-responsive">
              <table class="table border-bottom mb-5">
          <thead class="text-center">
            <tr class="bg-light">
              <th scope="col">#</th>
              <th scope="col" >Charge Type</th>
              <th scope="col">Item No</th>
              <th scope="col" >Description</th>
              <th scope="col" >Quantity</th>
              <th scope="col" >Units of Measure</th>
              <th scope="col" >Unit Price</th>
              <th scope="col" >Amount</th>
              <th scope="col"></th>

            </tr>
          </thead>

          <tbody id="table-body" class="fields" >
 	<%# <% @invoice.invoice_lines.each do |invoice_line| %>
              <%= f.fields_for :invoice_line do |ff| %>
                <%= render partial: 'field', locals: {ff: ff} %>
              <% end %>
           <%# <% end  %>

           
          </tbody>

        </table>
 </div>

<div class="row border border-dark p-2">
  <%= link_to "Add Product", add_field_path(format: :js), {method: :post, remote: true, id: "addProductBtn", class: 'btn btn-primary'} %>

      <div class="col">

      </div>

      <div class="col">
        <div class="row">
          <div class="col">
            Sub Total:
          </div>
          <div class="col">
            <!--  we need to fix the precision on the totals at some point 
            $ <= @invoice.amount_due %> -->
          </div>
        </div>

        <div class="row font-weight-bold">
          <div class="col">
            Grand Total Due:
          </div>
          <div class="col">
            <!--  we need to fix the precision on the totals at some point 
            $ <= @invoice.grand_total unless request.url.match('/invoices/new')%>  -->
          </div>
        </div>
      </div>
    </div>


    <div class="row action">
      <div class="col-10">
      </div>

      <div class="float-right col-2">
        <%= f.submit "Update Invoice", class: 'btn btn-primary' %>
      </div>

    </div>




<% end %>

<script type="text/javascript">


    function deleteRow(row){
      row.parentNode.deleteRow(row.rowIndex-1);
      return true;
    }

    var deleteBtns = document.getElementsByClassName("remove-field");

    for (var i=0; i<deleteBtns.length; i++){
      deleteBtns[i].addEventListener('click', function(e){
        e.preventDefault()
        var elem = e.target;
        var row = elem.parentNode.parentNode;
        deleteRow(row);
      });
    }
    $(".remove-field").on('click', function(e){
      e.preventDefault()
      var elem = e.target;
      var row = elem.parentNode.parentNode;
      deleteRow(row);
    });

    document.addEventListener("DOMContentLoaded", function(){

      let tBody = document.getElementById("table-body");
      let addBtn = document.getElementById("addProductBtn");

      function nameFields(){
        let selects = tBody.getElementsByTagName('select');
        for (var i=0;i < selects.length; i++){
          selects[i].name = `invoice[invoice_lines_attributes][${i}][invoice_id]`;
          selects[i].id = `invoice[invoice_lines_attributes][${i}][invoice_id]`;
          selects[i].parentElement.previousSibling.previousSibling.innerHTML = (i+1);
          selects[i].parentNode.nextSibling.nextElementSibling.firstElementChild.name = `invoice[invoice_lines_attributes][${i}][item_no]`;
          selects[i].parentNode.nextSibling.nextElementSibling.firstElementChild.id = `invoice[invoice_lines_attributes][${i}][description]`;

          selects[i].parentNode.nextSibling.nextElementSibling.firstElementChild.name = `invoice[invoice_lines_attributes][${i}][quantity]`;
          selects[i].parentNode.nextSibling.nextElementSibling.firstElementChild.id = `invoice[invoice_lines_attributes][${i}][units]`;



        }
      }

      function numberProducts(){
        let selects = tBody.getElementsByTagName('select');
        for (var i=0;i < selects.length; i++){
          selects[i].parentElement.previousSibling.previousSibling.append(i+1);
        }
      }

      addBtn.addEventListener('click', function(){
        setTimeout(nameFields, 300);
      })

      numberProducts();
    });








  </script>


</div>







<%= link_to 'Show', @invoice %> |
<%= link_to 'Back', invoices_path %>

app/views/invoices/myolds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Invoices</h1>
<div class="card">

<div class="table-responsive border-bottom" data-toggle="lists" data-lists-values='["js-lists-values-customer-name"]'>

  <%# <div class="search-form search-form--light m-3">
    <input type="text" class="form-control search" placeholder="Search">
    <button class="btn" type="button" role="button"><i class="material-icons">search</i></button>
  </div>
   %>
  <table class="table mb-0 thead-border-top-0">
  <thead>
    <tr>
      <th>Customer no</th>
      <th>Custoner name</th>
      <th>Contactno</th>
      <th>Contact name</th>
      <th>Address</th>
      <th>City</th>
      <th>Date</th>
      <th>Sale person code</th>
      <th>Sale person name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @invoices.each do |invoice| %>
      <tr>
        <td><%= invoice.customer_no %></td>
        <td><%= invoice.custoner_name %></td>
        <td><%= invoice.contactno %></td>
        <td><%= invoice.contact_name %></td>
        <td><%= invoice.address %></td>
        <td><%= invoice.city %></td>
        <td><%= invoice.date %></td>
        <td><%= invoice.sale_person_code %></td>
        <td><%= invoice.sale_person_name %></td>
        <td><%= link_to 'Show', invoice %></td>
        <td><%= link_to 'Edit', edit_invoice_path(invoice) %></td>
        <td><%= link_to 'Destroy', invoice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

</div>

</div>

<br>

<%= link_to 'New Invoice', new_invoice_path %>

app/views/invoices/myolds/new.html.erb
<h1 class="text-center">Create new Invoice</h1>



<div class="p-5 border-dark border mt-5">

  <%= render partial: 'invoice_form', locals: {invoice: @invoice}  %>

</div>

app/views/invoices/myolds/new1.html.erb
<h1>New Invoice</h1>

<%= render 'form', invoice: @invoice %>

<%= link_to 'Back', invoices_path %>

app/views/invoices/myolds/show.html.erb
<br><br>


<div class="invoice p-5">

  <% if @invoice %>
    <%= render partial: 'show_invoice', locals: {invoice: @invoice} %>
  <% else %>
    <h4>Invoice does not exist!</h4>
  <% end %>


</div>

app/views/invoices/myolds/show1.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Customer no:</strong>
  <%= @invoice.customer_no %>
</p>

<p>
  <strong>Custoner name:</strong>
  <%= @invoice.custoner_name %>
</p>

<p>
  <strong>Contactno:</strong>
  <%= @invoice.contactno %>
</p>

<p>
  <strong>Contact name:</strong>
  <%= @invoice.contact_name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @invoice.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @invoice.city %>
</p>

<p>
  <strong>Date:</strong>
  <%= @invoice.date %>
</p>

<p>
  <strong>Sale person code:</strong>
  <%= @invoice.sale_person_code %>
</p>

<p>
  <strong>Sale person name:</strong>
  <%= @invoice.sale_person_name %>
</p>

<%= link_to 'Edit', edit_invoice_path(@invoice) %> |
<%= link_to 'Back', invoices_path %>